/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 rose.gltf 
Author: heyyodd (https://sketchfab.com/heyyodd)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/piano-rose-fbf416d0f8d84cc198b0d5779d5e82ae
Title: piano rose
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/rose.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[26.019, 270.824, 3.108]} rotation={[-1.539, -0.067, 0.451]} scale={100}>
            <mesh geometry={nodes.stem_001_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.stem_001_Material001_0_1.geometry} material={materials['Material.001']} />
          </group>
          <mesh geometry={nodes.leaf_001_Material003_0.geometry} material={materials['Material.003']} position={[-42.4, 252.957, 9.291]} rotation={[-1.664, 0.259, 0.446]} scale={100} />
          <mesh geometry={nodes.leaf_002_Material003_0.geometry} material={materials['Material.003']} position={[-17.326, 245.496, 2.09]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.leaf_003_Material003_0.geometry} material={materials['Material.003']} position={[-16.754, 255.847, 36.156]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.leaf_004_Material003_0.geometry} material={materials['Material.003']} position={[64.729, 296.024, -30.934]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.leaf_005_Material003_0.geometry} material={materials['Material.003']} position={[53.642, 290.514, -15.696]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.leaf_006_Material003_0.geometry} material={materials['Material.003']} position={[38.805, 297.537, -33.976]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_021_Material_0.geometry} material={materials.Material} position={[20.794, 372.702, 20.447]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes['petal_001-5p_Material009_0'].geometry} material={materials['Material.009']} position={[26.598, 368.399, 5.791]} rotation={[-1.539, -0.067, 0.734]} scale={100} />
          <mesh geometry={nodes.petal_006_Material015_0.geometry} material={materials['Material.015']} position={[16.276, 374.509, 6.6]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_018_Material_0.geometry} material={materials.Material} position={[33.77, 373.945, 3.824]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes['petal_002-5p_Material008_0'].geometry} material={materials['Material.008']} position={[26.553, 366.001, 4.981]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_002_Material015_0.geometry} material={materials['Material.015']} position={[20.382, 375.763, 3.722]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes['petal_003-5p_Material007_0'].geometry} material={materials['Material.007']} position={[26.262, 362.566, 5.393]} rotation={[-1.539, -0.067, 0.065]} scale={100} />
          <mesh geometry={nodes.petal_009_Material015_0.geometry} material={materials['Material.015']} position={[29.804, 373.405, 13.713]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_013_Material_0.geometry} material={materials.Material} position={[34.843, 373.679, 8.864]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_019_Material_0.geometry} material={materials.Material} position={[37.074, 373.605, 9.763]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_028_Material_0.geometry} material={materials.Material} position={[38.799, 373.309, 9.785]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_027_Material_0.geometry} material={materials.Material} position={[35.77, 374.324, 2.392]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_026_Material_0.geometry} material={materials.Material} position={[33.561, 375.151, -4.005]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_031_Material_0.geometry} material={materials.Material} position={[35.285, 375.623, -6.723]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_008_Material015_0.geometry} material={materials['Material.015']} position={[30.682, 375.291, 4.896]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_007_Material015_0.geometry} material={materials['Material.015']} position={[17.339, 373.787, 1.683]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_011_Material015_0.geometry} material={materials['Material.015']} position={[14.911, 374.079, 0.707]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_010_Material015_0.geometry} material={materials['Material.015']} position={[15.906, 373.283, 6.429]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_003_Material015_0.geometry} material={materials['Material.015']} position={[27.425, 375.825, 4.994]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_015_Material015_0.geometry} material={materials['Material.015']} position={[13.929, 372.655, 7.17]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_022_Material_0.geometry} material={materials.Material} position={[16.299, 373.26, 16.677]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_012_Material015_0.geometry} material={materials['Material.015']} position={[25.589, 372.443, -1.236]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_016_Material015_0.geometry} material={materials['Material.015']} position={[25.262, 373.14, -3.26]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_017_Material015_0.geometry} material={materials['Material.015']} position={[31.379, 374.994, -0.785]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_025_Material_0.geometry} material={materials.Material} position={[22.508, 373.201, -4.856]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_030_Material_0.geometry} material={materials.Material} position={[9.06, 373.182, 8.76]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_032_Material_0.geometry} material={materials.Material} position={[34.869, 375.078, -7.213]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_035_Material_0.geometry} material={materials.Material} position={[36.968, 363.617, -11.54]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_029_Material_0.geometry} material={materials.Material} position={[32.902, 374.504, 17.738]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_033_Material014_0.geometry} material={materials['Material.014']} position={[39.323, 376.192, 0.323]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_005_Material015_0.geometry} material={materials['Material.015']} position={[19.502, 374.137, 12.017]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_041_Material010_0.geometry} material={materials['Material.010']} position={[5.753, 351.642, 2.493]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_004_Material015_0.geometry} material={materials['Material.015']} position={[27.386, 367.764, 12.389]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_023_Material_0.geometry} material={materials.Material} position={[9.996, 373.403, 8.884]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_036_Material013_0.geometry} material={materials['Material.013']} position={[6.916, 361.522, 5.58]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_024_Material_0.geometry} material={materials.Material} position={[12.916, 373.008, -0.387]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_001_Material015_0.geometry} material={materials['Material.015']} position={[20.612, 372.944, 9.599]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_034_Material_0.geometry} material={materials.Material} position={[32.996, 360.837, 21.101]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_038_Material_0.geometry} material={materials.Material} position={[17.774, 358.835, -11.088]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_039_Material_0.geometry} material={materials.Material} position={[16.607, 357.649, 21.148]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_040_Material006_0.geometry} material={materials['Material.006']} position={[34.838, 357.275, -12.957]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_020_Material_0.geometry} material={materials.Material} position={[32.199, 374.972, 15.356]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_014_Material015_0.geometry} material={materials['Material.015']} position={[19.179, 374.04, 15.397]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_042_Material011_0.geometry} material={materials['Material.011']} position={[36.645, 355.533, 21.495]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_037_Material012_0.geometry} material={materials['Material.012']} position={[44.681, 360.608, 4.643]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_043_Material005_0.geometry} material={materials['Material.005']} position={[40.898, 347.53, -2.163]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes.petal_044_Material004_0.geometry} material={materials['Material.004']} position={[26.46, 341.677, 20.926]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes['stem_002-1_Material002_0'].geometry} material={materials['Material.002']} position={[7.478, 244.821, 16.781]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes['stem_002-2_Material002_0'].geometry} material={materials['Material.002']} position={[34.731, 286.676, -14.253]} rotation={[-1.539, -0.067, 0.451]} scale={100} />
          <mesh geometry={nodes['���������������002_������_0'].geometry} material={materials.material} position={[29.004, 313.189, 1.543]} rotation={[-1.474, -0.067, -0.853]} scale={[50, 21.801, 50]} />
          <mesh geometry={nodes['���������������006_������_0'].geometry} material={materials.material} position={[29.18, 304.492, -0.974]} rotation={[-1.477, -0.092, 1.55]} scale={[50, 21.801, 50]} />
          <mesh geometry={nodes['���������������007_������_0'].geometry} material={materials.material} position={[27.091, 213.966, 8.247]} rotation={[-1.571, 0.051, -2.019]} scale={[50, 21.801, 50]} />
          <mesh geometry={nodes['���������������008_������_0'].geometry} material={materials.material} position={[29.244, 247.602, 0.894]} rotation={[-1.841, 0.067, 0.258]} scale={[50, 21.801, 50]} />
          <mesh geometry={nodes['���������������009_������_0'].geometry} material={materials.material} position={[27.767, 282.263, -0.894]} rotation={[-1.484, 0.004, -2.601]} scale={[50, 21.801, 50]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/rose.gltf')
